
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 22 16:50:37 WEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EMPILHA_VAR = 6;
  public static final int MOD = 15;
  public static final int ESCREVE_INT = 20;
  public static final int SMENOR = 18;
  public static final int SALTA = 19;
  public static final int REGRESSA = 4;
  public static final int SIGUAL = 17;
  public static final int EMPILHA = 8;
  public static final int ATRIBUI_ARG = 10;
  public static final int DOIS_PONTOS = 26;
  public static final int INTEIRO = 24;
  public static final int EXP = 16;
  public static final int EMPILHA_ARG = 7;
  public static final int SUB = 12;
  public static final int STRING = 25;
  public static final int EOF = 0;
  public static final int MULT = 13;
  public static final int DIV = 14;
  public static final int ESCREVE_STR = 21;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 23;
  public static final int MUDA_LINHA = 22;
  public static final int CHAMA = 2;
  public static final int ATRIBUI_VAR = 9;
  public static final int ERRO = 27;
  public static final int SOMA = 11;
  public static final int COLOCA_ARG = 5;
  public static final int LOCAIS = 3;
}

